### ISSUE TITLE
Missing timeouts for protocol operations

### ISSUE THREAD

**Issue by jonnor** [flowbased/fbp-spec#12]
Either in runner.coffee or in protocol.coffee. For startNetwork, stopNetwork, sendPacket etc.
Together with #11, probably should be put in a general facility to ensure consistent behavior.

runner must respect the timeouts set in the spec files, and report them.

**Comment by jonnor** [comment]
For this it would be useful to have FBP runtime protocol implementation(s) where one could filter/remove/mangle data returned, to stimulate these cases.

Maybe even have such behavior programmed over the transport (WebSocket etc)? Could then add it to the Python runtime example, or a similar tool.

**Comment by bergie** [comment]
Note: we get timeouts "for free" with fbp-client, see #144
