### ISSUE TITLE
Sending to multiple input ports

### ISSUE THREAD

**Issue by jpaulm** [flowbased/fbp-spec#13]
I saw in the Readme

>You can send data to multiple inports and check expectations on multiple ports per testcase:

I must admit that I don't really understand what I assume is an example of this (below the quoted line), but it *sounds* very different from "classical" FBP.  So my question is whether there are any plans to accommodate "classical" FBP in fbp-spec, esp. as the preamble says: 
>A runtime-independent test framework for Flow Based Programming (FBP) component and graphs

TIA

**Comment by bergie** [comment]
@jpaulm in fbp-spec each graph (or component) being tested can have multiple exported inports or outports. Separate packets can be sent to any combination of input ports, and separate packets can be inspected from the output ports.

For example, if you have a `math/Add` component with inports `ADDEND` and `AUGEND`, and a outport `SUM`, you could send packets with int values 4 & 2 to the inports, and expect the `SUM` port to send a 6 out.

I don't see that as being particularly non-classical :-)

**Comment by jpaulm** [comment]
Thanks, for the prompt answer, @bergie !  I get it - so that's just FBP business as usual!   I guess I read it as meaning that the data could come from *one* output port and be sent to multiple input ports *within a network* - but that's not what was meant.  Good news!

**Comment by bergie** [comment]
great! closing the ticket, then :-)
