### ISSUE TITLE
Make fbp-client command timeout configurable

### ISSUE THREAD

**Issue by bergie** [flowbased/fbp-spec#147]
Right now fbp-client command timeout is quite low (1000ms). We may want to make that configurable for tests that can take a longer time to set up or shut down (especially `network.start` and `network.stop`)

https://github.com/flowbased/fbp-client/blob/master/lib/client.js#L21

Refs: flowhub/bigiot-bridge#40 where tests occasionally fail because it takes a while for the web server to close (which is part of `network.stop`)

**Comment by jonnor** [comment]
Fixed in #152
