### ISSUE TITLE
Inconsistent results when run inside Flowhub

### ISSUE THREAD

**Issue by bergie** [flowbased/fbp-spec#8]
Here is how Flowhub triggers fbp-spec (with a pre-existing runtime connection): https://github.com/noflo/noflo-ui/blob/master/components/RunTests.coffee

However, the results are inconsistent when shown in the UI:

<img width="479" alt="screen shot 2015-08-26 at 20 05 05" src="https://cloud.githubusercontent.com/assets/3346/9502792/99d6b8ca-4c33-11e5-9571-b99f777c468b.png">

This doesn't conform to what I see in the runtime console where the states appear to be what was expected:

```
undefined 'Portal c-base space station is L4 RESISTANCE'
undefined 'Portal c-base space station is L8 RESISTANCE'
undefined 'Portal c-base space station is L8 ALIENS'
undefined 'Portal c-base space station (NEUTRAL) is L8 and has disco'
undefined 'Portal c-base space station is L8 RESISTANCE'
undefined 'Portal c-base space station has special disco mods'
undefined 'Portal c-base space station has special disco mods’
```

When the same tests are run inside Node.js Mocha runner, they all pass: https://travis-ci.org/c-base/ingress-table/builds/77374093#L446

**Comment by bergie** [comment]
Similar thing appears to happen when running multiple suites, with the latter suite receiving the output of the first one:

<img width="408" alt="screen shot 2015-08-26 at 20 52 56" src="https://cloud.githubusercontent.com/assets/3346/9502956/80809a34-4c34-11e5-952c-0b2fe311bdd0.png">

These also pass with Node.js Mocha: https://travis-ci.org/noflo/noflo-hackrf/builds/77363801#L221

**Comment by jonnor** [comment]
Probably something in [runner.coffee](https://github.com/flowbased/fbp-spec/blob/master/src/runner.coffee), in which case it should also manifest when running tests with `fbp-spec` executable.

**Comment by jonnor** [comment]
Could also be that if the runtime sends messages from an old network, we don't properly ignore them.
Possibly related to that we (currently) never send a `network:stop` message.

**Comment by jonnor** [comment]
Think I solved the Ingress Table issue in https://github.com/c-base/ingress-table/commit/c5241731ae4dafd15aceb7a8373ca39a254b26c2
