### ISSUE TITLE
Support multiple sets of input and output messages

### ISSUE THREAD

**Issue by jonnor** [flowbased/fbp-spec#9]
Needed for some (stateful) components. Like for instance in microflo-core HysteresisLatch:
https://github.com/microflo/microflo-core/blob/master/spec/HysteresisLatch.yaml#L48

Should let the `inputs` and `expect` keys optionally take an array of objects, in addition to the object directly.

**Comment by bergie** [comment]
This would help greatly with https://github.com/c-base/ingress-table/blob/master/spec/CalculateState.yaml tests too, so we could test against state changes like `attack` or `upgrade`
