### ISSUE TITLE
Hangs forever if command does not write to stdout

### ISSUE THREAD

**Issue by jonnor** [flowbased/fbp-spec#93]
It is used as a proxy for whether the runtime is ready to accept connections. Which is very hacky.
Instead we should periodically try to open the runtime connection, and if it does not succeed with a certain time, fail with an explanatory error

**Comment by bergie** [comment]
Here is how we handled the "is runtime ready" question for IFRAME runtimes:

https://github.com/flowbased/fbp-protocol-client/blob/master/src/iframe.coffee#L95

With iframes, the connection logic is such that the runtime might not be ready when the iframe is loaded, as it needs to run some JS first.
